-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE task (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    due_date TIMESTAMP NOT NULL,
    completed VARCHAR(255) NOT NULL,
    CONSTRAINT title_constraint CHECK (length(title) >= 4 AND length(title) <= 32),
    CONSTRAINT description_constraint CHECK (length(description) >= 8 AND length(description) <= 64)
);
